#!/bin/sh
# $Id: files_vboxsf $
## @file
# Shared file between Makefile.kmk and export_modules.sh.
#

#
# Copyright (C) 2007-2023 Oracle and/or its affiliates.
#
# This file is part of VirtualBox base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

FILES_VBOXSF_NOBIN=" \
    ${PATH_ROOT}/include/iprt/nocrt/limits.h=>include/iprt/nocrt/limits.h \
    ${PATH_ROOT}/include/iprt/alloc.h=>include/iprt/alloc.h \
    ${PATH_ROOT}/include/iprt/asm.h=>include/iprt/asm.h \
    ${PATH_ROOT}/include/iprt/asm-amd64-x86.h=>include/iprt/asm-amd64-x86.h \
    ${PATH_ROOT}/include/iprt/asm-math.h=>include/iprt/asm-math.h \
    ${PATH_ROOT}/include/iprt/assert.h=>include/iprt/assert.h \
    ${PATH_ROOT}/include/iprt/assertcompile.h=>include/iprt/assertcompile.h \
    ${PATH_ROOT}/include/iprt/cdefs.h=>include/iprt/cdefs.h \
    ${PATH_ROOT}/include/iprt/err.h=>include/iprt/err.h \
    ${PATH_ROOT}/include/iprt/errcore.h=>include/iprt/errcore.h \
    ${PATH_ROOT}/include/iprt/fs.h=>include/iprt/fs.h \
    ${PATH_ROOT}/include/iprt/latin1.h=>include/iprt/latin1.h \
    ${PATH_ROOT}/include/iprt/list.h=>include/iprt/list.h \
    ${PATH_ROOT}/include/iprt/log.h=>include/iprt/log.h \
    ${PATH_ROOT}/include/iprt/mangling.h=>include/iprt/mangling.h \
    ${PATH_ROOT}/include/iprt/mem.h=>include/iprt/mem.h \
    ${PATH_ROOT}/include/iprt/memobj.h=>include/iprt/memobj.h \
    ${PATH_ROOT}/include/iprt/param.h=>include/iprt/param.h \
    ${PATH_ROOT}/include/iprt/path.h=>include/iprt/path.h \
    ${PATH_ROOT}/include/iprt/semaphore.h=>include/iprt/semaphore.h \
    ${PATH_ROOT}/include/iprt/stdarg.h=>include/iprt/stdarg.h \
    ${PATH_ROOT}/include/iprt/stdint.h=>include/iprt/stdint.h \
    ${PATH_ROOT}/include/iprt/string.h=>include/iprt/string.h \
    ${PATH_ROOT}/include/iprt/time.h=>include/iprt/time.h \
    ${PATH_ROOT}/include/iprt/types.h=>include/iprt/types.h \
    ${PATH_ROOT}/include/iprt/uint64.h=>include/iprt/uint64.h \
    ${PATH_ROOT}/include/iprt/uni.h=>include/iprt/uni.h \
    ${PATH_ROOT}/include/iprt/utf16.h=>include/iprt/utf16.h \
    ${PATH_ROOT}/include/iprt/x86-helpers.h=>include/iprt/x86-helpers.h \
    ${PATH_ROOT}/include/iprt/linux/version.h=>include/iprt/linux/version.h \
    ${PATH_ROOT}/include/VBox/cdefs.h=>include/VBox/cdefs.h \
    ${PATH_ROOT}/include/VBox/err.h=>include/VBox/err.h \
    ${PATH_ROOT}/include/VBox/log.h=>include/VBox/log.h \
    ${PATH_ROOT}/include/VBox/ostypes.h=>include/VBox/ostypes.h \
    ${PATH_ROOT}/include/VBox/param.h=>include/VBox/param.h \
    ${PATH_ROOT}/include/VBox/shflsvc.h=>include/VBox/shflsvc.h \
    ${PATH_ROOT}/include/VBox/types.h=>include/VBox/types.h \
    ${PATH_ROOT}/include/VBox/VBoxGuest.h=>include/VBox/VBoxGuest.h \
    ${PATH_ROOT}/include/VBox/VBoxGuestCoreTypes.h=>include/VBox/VBoxGuestCoreTypes.h \
    ${PATH_ROOT}/include/VBox/VBoxGuestLib.h=>include/VBox/VBoxGuestLib.h \
    ${PATH_ROOT}/include/VBox/VBoxGuestLibSharedFolders.h=>include/VBox/VBoxGuestLibSharedFolders.h \
    ${PATH_ROOT}/include/VBox/VBoxGuestLibSharedFoldersInline.h=>include/VBox/VBoxGuestLibSharedFoldersInline.h \
    ${PATH_ROOT}/include/VBox/VBoxGuestMangling.h=>include/VBox/VBoxGuestMangling.h \
    ${PATH_ROOT}/include/VBox/VMMDev.h=>include/VBox/VMMDev.h \
    ${PATH_ROOT}/include/VBox/VMMDevCoreTypes.h=>include/VBox/VMMDevCoreTypes.h \
    ${PATH_ROOT}/src/VBox/Additions/common/VBoxGuest/lib/VBoxGuestR0LibInternal.h=>VBoxGuestR0LibInternal.h \
    ${PATH_ROOT}/src/VBox/Additions/common/VBoxGuest/lib/VBoxGuestR0LibGenericRequest.cpp=>VBoxGuestR0LibGenericRequest.c \
    ${PATH_ROOT}/src/VBox/Additions/common/VBoxGuest/lib/VBoxGuestR0LibHGCM.cpp=>VBoxGuestR0LibHGCM.c \
    ${PATH_ROOT}/src/VBox/Additions/common/VBoxGuest/lib/VBoxGuestR0LibIdc.cpp=>VBoxGuestR0LibIdc.c \
    ${PATH_ROOT}/src/VBox/Additions/common/VBoxGuest/lib/VBoxGuestR0LibIdc-unix.cpp=>VBoxGuestR0LibIdc-unix.c \
    ${PATH_ROOT}/src/VBox/Additions/common/VBoxGuest/lib/VBoxGuestR0LibInit.cpp=>VBoxGuestR0LibInit.c \
    ${PATH_ROOT}/src/VBox/Additions/common/VBoxGuest/lib/VBoxGuestR0LibPhysHeap.cpp=>VBoxGuestR0LibPhysHeap.c \
    ${PATH_ROOT}/src/VBox/Additions/common/VBoxGuest/lib/VBoxGuestR0LibSharedFolders.c=>VBoxGuestR0LibSharedFolders.c \
    ${PATH_ROOT}/src/VBox/Installer/linux/Makefile-header.gmk=>Makefile-header.gmk \
    ${PATH_ROOT}/src/VBox/Installer/linux/Makefile-footer.gmk=>Makefile-footer.gmk \
    ${PATH_ROOT}/src/VBox/Runtime/common/math/gcc/divdi3.c=>divdi3.c \
    ${PATH_ROOT}/src/VBox/Runtime/common/math/gcc/moddi3.c=>moddi3.c \
    ${PATH_ROOT}/src/VBox/Runtime/common/math/gcc/qdivrem.c=>qdivrem.c \
    ${PATH_ROOT}/src/VBox/Runtime/common/math/gcc/quad.h=>quad.h \
    ${PATH_ROOT}/src/VBox/Runtime/common/math/gcc/udivdi3.c=>udivdi3.c \
    ${PATH_ROOT}/src/VBox/Runtime/common/math/gcc/udivmoddi4.c=>udivmoddi4.c \
    ${PATH_ROOT}/src/VBox/Runtime/common/math/gcc/umoddi3.c=>umoddi3.c \
    ${PATH_ROOT}/src/VBox/Runtime/r0drv/linux/the-linux-kernel.h=>r0drv/linux/the-linux-kernel.h \
    ${PATH_ROOT}/src/VBox/Additions/linux/sharedfolders/Makefile.module=>Makefile \
    ${PATH_ROOT}/src/VBox/Additions/linux/sharedfolders/dirops.c=>dirops.c \
    ${PATH_ROOT}/src/VBox/Additions/linux/sharedfolders/lnkops.c=>lnkops.c \
    ${PATH_ROOT}/src/VBox/Additions/linux/sharedfolders/regops.c=>regops.c \
    ${PATH_ROOT}/src/VBox/Additions/linux/sharedfolders/utils.c=>utils.c \
    ${PATH_ROOT}/src/VBox/Additions/linux/sharedfolders/vbsfmount.h=>vbsfmount.h \
    ${PATH_ROOT}/src/VBox/Additions/linux/sharedfolders/vfsmod.c=>vfsmod.c \
    ${PATH_ROOT}/src/VBox/Additions/linux/sharedfolders/vfsmod.h=>vfsmod.h \
    ${PATH_OUT}/version-generated.h=>version-generated.h \
    ${PATH_OUT}/revision-generated.h=>revision-generated.h \
    ${PATH_OUT}/product-generated.h=>product-generated.h \
"

FILES_VBOXSF_BIN=" \
"
