# $Id: Makefile.kmk $
## @file
# VirtualBox Validation Kit - API Tests.
#

#
# Copyright (C) 2006-2023 Oracle and/or its affiliates.
#
# This file is part of VirtualBox base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# The contents of this file may alternatively be used under the terms
# of the Common Development and Distribution License Version 1.0
# (CDDL), a copy of it is provided in the "COPYING.CDDL" file included
# in the VirtualBox distribution, in which case the provisions of the
# CDDL are applicable instead of those of the GPL.
#
# You may elect to license modified versions of this file under the
# terms and conditions of either the GPL or the CDDL or both.
#
# SPDX-License-Identifier: GPL-3.0-only OR CDDL-1.0
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk


INSTALLS += ValidationKitTestsApi
ValidationKitTestsApi_TEMPLATE = VBoxValidationKitR3
ValidationKitTestsApi_INST = $(INST_VALIDATIONKIT)tests/api/
ValidationKitTestsApi_EXEC_SOURCES := \
	$(PATH_SUB_CURRENT)/tdApi1.py \
	$(PATH_SUB_CURRENT)/tdAppliance1.py \
	$(PATH_SUB_CURRENT)/tdCloneMedium1.py \
	$(PATH_SUB_CURRENT)/tdCreateVMWithDefaults1.py \
	$(PATH_SUB_CURRENT)/tdMoveMedium1.py \
	$(PATH_SUB_CURRENT)/tdMoveVm1.py \
	$(PATH_SUB_CURRENT)/tdPython1.py \
	$(PATH_SUB_CURRENT)/tdTreeDepth1.py

ifndef VBOX_OSE
 ValidationKitTestsApi_EXEC_SOURCES += \
 	$(PATH_SUB_CURRENT)/tdCloud1.py \
 	$(PATH_SUB_CURRENT)/tdOciConnection1.py \
 	$(PATH_SUB_CURRENT)/tdOciExport1.py \
 	$(PATH_SUB_CURRENT)/tdOciImage1.py \
 	$(PATH_SUB_CURRENT)/tdOciImport1.py \
 	$(PATH_SUB_CURRENT)/tdOciInstance1.py \
 	$(PATH_SUB_CURRENT)/tdOciProfile1.py
endif
ValidationKitTestsApi_SOURCES := \
	$(wildcard \
	$(PATH_SUB_CURRENT)/*.ova \
	)

VBOX_VALIDATIONKIT_PYTHON_SOURCES += $(ValidationKitTestsApi_EXEC_SOURCES)

$(evalcall def_vbox_validationkit_process_python_sources)
include $(FILE_KBUILD_SUB_FOOTER)
