/* $Id: locators.h $ */
/** @file
 * Placeholder "locators.h" that wsmousevar.h needs (bad hygiene).
 *
 * It's normally generated by config(8), but see the explanatory
 * comment in vboxguest.ioconf
 */
#define WSMOUSEDEVCF_MUX 0
