=head1 NAME

TPM_IO_TpmEstablished_Get   - get the value of the TPMEstablished flag

TPM_IO_TpmEstablished_Reset - reset the TPMEstablished flag

=head1 LIBRARY

TPM library (libtpms, -ltpms)

=head1 SYNOPSIS

B<#include <libtpms/tpm_types.h>>

B<#include <libtpms/tpm_tis.h>>

B<#include <libtpms/tpm_error.h>>

B<TPM_RESULT TPM_IO_TpmEstablished_Get(TPM_BOOL> *I<tpmEstablished>B<);>

B<TPM_RESULT TPM_IO_TpmEstablished_Reset(void);>

=head1 DESCRIPTION

The B<TPM_IO_TpmEstablished_Get()> function returns the value of the 
TPMEstablished flag of the TPM's permanent data. 

The B<TPM_IO_TpmEstablished_Reset()> function resets the TPMEstablished
flag.

=head1 ERRORS

=over 4

=item B<TPM_SUCCESS>

The function completed successfully.

=item B<TPM_FAIL>

General failure.

=item B<TPM_BAD_LOCALITY>

The locality used for resetting the flags is wrong.

=back

For a complete list of TPM error codes please consult the include file
B<libtpms/tpm_error.h>

=head1 SEE ALSO

B<TPMLIB_MainInit>(3), B<TPMLIB_Terminate>(3), B<TPMLIB_RegisterCallbacks>(3),
B<TPMLIB_Process>(3), B<TPM_IO_Hash_Start>(3), B<TPM_IO_Hash_End>(3),
B<TPM_IO_Hash_Data>(3)

=cut
