=head1 NAME

TPMLIB_CancelCommand  - Cancel a TPM command

=head1 LIBRARY

TPM library (libtpms, -ltpms)

=head1 SYNOPSIS

B<#include <libtpms/tpm_library.h>>

B<uint32_t TPMLIB_CancelCommand(void);>

=head1 DESCRIPTION

The B<TPMLIB_CancelCommand()> function indicates that the ongoing processing
of a TPM command is to be cancelled. The cancellation will only
be effective for certain time consuming operations, such as the creation
of keys.

Note that an implementation that wants to support cancellation of commands
needs to process TPM commands in one thread and cancel them in another.

=head1 SEE ALSO

B<TPMLIB_Process>(3)

=cut
