=head1 NAME

TPMLIB_GetVersion  - Get the version of the TPM library

=head1 LIBRARY

TPM library (libtpms, -ltpms)

=head1 SYNOPSIS

B<#include <libtpms/tpm_library.h>>

B<uint32_t TPMLIB_GetVersion(void);>

=head1 DESCRIPTION

The B<TPMLIB_GetVersion()> function returns the libtpms library version.
The TPM library version is formatted as follows:

	Bits 0 - 7  : revision of the library
	Bits 8 -15  : minor version number of the library
	Bits 16-23  : major version number of the library

V0.5.1 is therefore represented as 0x00000501.

=head1 SEE ALSO

B<TPMLIB_MainInit>(3), B<TPMLIB_Terminate>(3)

=cut
