=head1 NAME

TPMLIB_SetBufferSize  - Set the TPM's I/O buffer size

=head1 LIBRARY

TPM library (libtpms, -ltpms)

=head1 SYNOPSIS

B<#include <libtpms/tpm_library.h>>

B<uint32_t TPMLIB_SetBufferSize(uint32_t, uint32_t *, uint32_t *);>

=head1 DESCRIPTION

The B<TPMLIB_SetBufferSize()> function sets the size of the buffer
the TPM can use for input and output and that it advertises to users.
It also allows to get the minimum and maximum supported buffer
size.

If 0 is given on input, the currently used buffer size is returned.
Any other number will try to change the buffer size. The returned
size may be smaller than the requested one, if the requested one was
above a maximum. The returned size may be larger than the requested
one, if the requested one was below a minimum.

This function must be called after B<TPMLIB_ChooseTPMVersion()> has
been called. It should not be called after B<TPMLIB_MainInit()> has
been called but can again be called once B<TPMLIB_Terminate()> has
been called.

=head1 SEE ALSO

B<TPMLIB_ChooseTPMVersion>(3), B<TPMLIB_MainInit>(3), B<TPMLIB_Terminate>(3)

=cut
